import { Button } from '../components/button'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <title>Astro + TailwindCSS</title>
      </head>

      <body>
        <div className="grid place-items-center h-screen content-center">
          <Button>Tailwind Button in NextJS!</Button>
        </div>
      </body>
    </html>
  )
}
